Commented out trufflehog and added render hook

diff --git a/.github/workflows/cicdpipeline.yaml b/.github/workflows/cicdpipeline.yaml
--- a/.github/workflows/cicdpipeline.yaml
+++ b/.github/workflows/cicdpipeline.yaml
@@ -22,29 +22,35 @@ jobs:
       - name: Install dependencies
         run: npm ci  # Install dependencies (corrected the npm command)
 
-      - run: echo "Pipeline run successfully. Have a great day! status ${{ job.status }}"
+  # TruffleHog:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     # Checkout code to ensure TruffleHog has access to the repository
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0  # Fetch full history for scanning
 
-  TruffleHog:
+  #     # Scan the entire branch using TruffleHog
+  #     - name: Scan entire branch for secrets
+  #       id: trufflehog_scan
+  #       uses: trufflesecurity/trufflehog@main
+  #       with:
+  #         base: ""  # Empty base to scan from the beginning of the branch
+  #         head: ${{ github.ref_name }}  # Current branch reference
+  #         extra_args: --results=verified,unknown  # Only include verified and unknown secrets
+
+  #     # Check if TruffleHog scan failed (i.e., secrets were found) and fail the build
+  #     - name: Fail the build on secret detection
+  #       if: steps.trufflehog_scan.outcome == 'failure'  # If secrets are found
+  #       run: |
+  #         echo "TruffleHog detected secrets. Failing the build."
+  #         exit 1  # Force failure
+
+  Render:
     runs-on: ubuntu-latest
     steps:
-      # Checkout code to ensure TruffleHog has access to the repository
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0  # Fetch full history for scanning
+      - name: Render Hook
+        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
 
-      # Scan the entire branch using TruffleHog
-      - name: Scan entire branch for secrets
-        id: trufflehog_scan
-        uses: trufflesecurity/trufflehog@main
-        with:
-          base: ""  # Empty base to scan from the beginning of the branch
-          head: ${{ github.ref_name }}  # Current branch reference
-          extra_args: --results=verified,unknown  # Only include verified and unknown secrets
-
-      # Check if TruffleHog scan failed (i.e., secrets were found) and fail the build
-      - name: Fail the build on secret detection
-        if: steps.trufflehog_scan.outcome == 'failure'  # If secrets are found
-        run: |
-          echo "TruffleHog detected secrets. Failing the build."
-          exit 1  # Force failure
+      - run: echo "Pipeline run successfully. Have a great day! status ${{ job.status }}"
